{application,fix_engine,
             [{description,"FIX protocol engine implementation in super Erlang"},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib,ranch]},
              {mod,{fix_engine_app,[]}},
              {env,[]},
              {modules,[fix_comp,fix_encoder_decoder,fix_engine,
                        fix_engine_app,fix_engine_sup,fix_field,fix_protocol,
                        fix_type,protocol_encoder,test_logon]}]}.
